version: '3'
services:
  watermill:
    image: golang:1.12
    command: /bin/true
    volumes:
      - .:/app
      - .mod-cache:/go/pkg/mod
    working_dir: /app

    environment:
      WATERMILL_TEST_KAFKA_BROKERS: kafka:9091,kafka:9092,kafka:9093,kafka:9094,kafka:9095

  kafka1:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,PLAINTEXT_HOST://kafka:29091

  kafka2:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092

  kafka3:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://kafka:29093

  kafka4:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,PLAINTEXT_HOST://kafka:29094

  kafka5:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://kafka:29095


